<?php
/**
 * @file
 */

use Dennis\Link\Checker\Config;
use Dennis\Link\Checker\Logger;
use Dennis\Link\Checker\LinkLocalisation;
use Dennis\Link\Checker\EntityHandler;
use Dennis\Link\Checker\Throttler;
use Dennis\Link\Checker\Database;
use Dennis\Link\Checker\Queue;

use Dennis\Asset\Checker\AssetProcessor;
use Dennis\Asset\Checker\AssetAnalyser;

/**
 * PSR-4 autoloader
 * files[] in .info doesn't find them.
 */
spl_autoload_register(function ($class) {
  if (strpos($class, 'Dennis\Asset\Checker\Asset') === 0) {
    if (file_exists((__DIR__ . '/src/' . str_replace('\\', '/', $class) . '.php'))) {
      include(__DIR__ . '/src/' . str_replace('\\', '/', $class) . '.php');
    }
  }
});

/**
 * Setup the link processor.
 *
 * @param array $nids
 * @return \Dennis\Asset\Checker\AssetProcessor
 */
function dennis_asset_checker_setup(array $nids) {
  $site_host = parse_url(dennis_ga_get_live_url(), PHP_URL_HOST);
  $config = (new Config())
    ->setLogger((new Logger())->setVerbosity(Logger::VERBOSITY_HIGH))
    ->setSiteHost($site_host)
    ->setMaxRedirects(10)
    ->setInternalOnly(TRUE)
    ->setLocalisation(LinkLocalisation::ORIGINAL)
    ->setFieldNames(variable_get('dennis_link_checker_fields', array('body')))
    ->setNodeList($nids);

  $queue = new Queue('dennis_asset_checker');
  $entity_handler = new EntityHandler($config);

  // Make sure we don't request more than one page per second.
  $curl_throttler = new Throttler(1);

  // Database object that allows interaction with the DB.
  $database = new Database();

  $analyzer = new AssetAnalyser($config, $curl_throttler, $database);

  return new AssetProcessor($config, $queue, $entity_handler, $analyzer);
}

/**
 * Run the link checker queue.
 *
 * @param array $nids
 */
function dennis_asset_checker_run(array $nids) {
  $processor = dennis_asset_checker_setup($nids);
  //$processor->setTimeLimit(20); // temporarily low time limit.
  $processor->run();
}
