<?php
/**
 * @file
 */

use Dennis\Link\Checker\Config;
use Dennis\Link\Checker\Logger;
use Dennis\Link\Checker\LinkLocalisation;
use Dennis\Link\Checker\Processor;
use Dennis\Link\Checker\EntityHandler;
use Dennis\Link\Checker\Analyzer;
use SystemQueue as Queue;

/**
 * PSR-4 autoloader
 * files[] in .info doesn't find them.
 */
spl_autoload_register(function ($class) {
  if (strpos($class, 'Dennis\Link\Checker') === 0) {
    if (file_exists((__DIR__ . '/src/' . str_replace('\\', '/', $class) . '.php'))) {
      include(__DIR__ . '/src/' . str_replace('\\', '/', $class) . '.php');
    }
  }
});

/**
 * Run the link checker queue.
 */
function dennis_link_checker_run() {
  $site_host = parse_url(dennis_ga_get_live_url(), PHP_URL_HOST);
  $config = (new Config())
    ->setLogger((new Logger())->setVerbosity(Logger::VERBOSITY_HIGH))
    ->setSiteHost($site_host)
    ->setMaxRedirects(10)
    ->setInternalOnly(TRUE)
    ->setLocalisation(LinkLocalisation::ORIGINAL);

  $queue = new Queue('dennis_link_checker');
  $entity_handler = new EntityHandler($config);
  $analyzer = new Analyzer($config);
  $processor = new Processor($config, $queue, $entity_handler, $analyzer);
  //$processor->setTimeLimit(20); // temporarily low time limit.
  $processor->run();
}
